### PR TITLE
fix: add missing write function on context logger

### PR DESCRIPTION
**Pull request by fengmk2**
This change is [Reviewable](https://reviewable.io/reviews/eggjs/egg-logger/5)

### CODE REVIEW

**Comment by popomore** [comment]
+1

**Comment by popomore** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/eggjs/egg-logger/5)*

**Comment by fengmk2** [comment]
我发个版本。

**Comment by fengmk2** [comment]
1.1.1

**Pull request merged**
